### ISSUE TITLE
count_characters does not work anymore in 2.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [miroshnikov/jsmart#36]
```
What steps will reproduce the problem?
1. Use the modifier in a template: {$number = $label|count_characters}
2. Use jSmart Version 2.10 (the modifier works in 2.9)

Firebug gives the following error:
Error: a.replace is not a function in count_characters(count_characters__p0)




```

Original issue reported on code.google.com by `i...@tourispo.com` on 9 Dec 2013 at 6:13
